package com.everyday.everyday_glasses

import android.graphics.Canvas
import android.graphics.RectF

/**
 * Base class for dashboard controls that reveal themselves when their square is hovered.
 *
 * Hover controls intentionally stay lighter than widgets: they do not participate in widget
 * z-order, dragging, or resizing. Placement is driven by a dashboard grid by calling [setBounds].
 *
 * Subclasses can optionally consume raw cursor events ([onCursorDown] / [onCursorMove] /
 * [onCursorUp]) when they need richer interaction than a simple tap (e.g. the lemon-slice
 * selector that magnifies on press).
 */
abstract class BaseHoverControl(
    val id: String,
    val label: String,
    size: Float
) {
    val bounds = RectF()

    var size: Float = size
        private set

    var isHovered: Boolean = false
        private set

    /**
     * Whether this control currently occupies a slot on the dashboard. Unplaced controls
     * skip hover/tap/draw, but their bounds are preserved so the editor can re-place them.
     */
    var isPlaced: Boolean = true

    fun setBounds(left: Float, top: Float, size: Float = this.size) {
        this.size = size
        bounds.set(left, top, left + size, top + size)
    }

    fun updateHover(px: Float, py: Float) {
        isHovered = isPlaced && containsPoint(px, py)
    }

    fun clearHover() {
        isHovered = false
    }

    /**
     * The point-containment test used for hover/tap dispatch. Subclasses may override to
     * include an expanded interactive area (e.g. the magnified lemon).
     */
    open fun containsPoint(px: Float, py: Float): Boolean = bounds.contains(px, py)

    open fun handleTap(px: Float, py: Float): Boolean {
        if (!isPlaced) return false
        if (!containsPoint(px, py)) return false
        performAction()
        return true
    }

    open fun handleDoubleTap(px: Float, py: Float): Boolean = false

    open fun draw(canvas: Canvas) {
        if (!isPlaced || !isHovered) return
        drawHovered(canvas)
    }

    /**
     * Renders the control unconditionally (used by the layout editor where the controls
     * are always visible regardless of hover state).
     */
    open fun drawForEditor(canvas: Canvas) {
        drawHovered(canvas)
    }

    /**
     * Subclasses with stateful interactions (long press, slide-to-select) override these
     * three hooks to consume the cursor pipeline. Default behaviour: ignore.
     */
    open fun onCursorDown(px: Float, py: Float): Boolean = false
    open fun onCursorMove(px: Float, py: Float, dx: Float, dy: Float): Boolean = false
    open fun onCursorUp(px: Float, py: Float): Boolean = false

    /** True while the control is mid-interaction and should keep receiving cursor events. */
    open fun isInteracting(): Boolean = false

    /**
     * True when movement during a captured press should be routed to the control without
     * moving the shared app cursor.
     */
    open fun freezesCursorWhileInteracting(): Boolean = false

    /**
     * Return true when the tap generated by the current cursor-up should be ignored.
     * Stateful controls use this when a release changes mode instead of activating.
     */
    open fun shouldGuardTapAfterCursorUp(): Boolean = false

    /** Cancel any in-progress interaction (called when another modal takes focus). */
    open fun cancelInteraction() {}

    protected abstract fun drawHovered(canvas: Canvas)

    protected open fun performAction() {}
}
